<?php

namespace Database\Seeders;

use App\Models\Insumo;
use App\Models\Team;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsumoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    private $insumosComMedida = [
        'Algodão bolinha c/ 100' => ['unidade', 100], // 100 unidades por pacote
        'Álcool 70% (100ml)' => ['frasco', 1], // 1 frasco de 100ml
        'Álcool 70% (Swaab) c/ 200' => ['frasco', 200], // 1 frasco de 100ml
        'Absorvente Mili Noturno c/ 32' => ['unidade', 32],
        'Absorvente Mili Simples c/ 32' => ['unidade', 32],
        'Gaze 13 fios 7,5cm x 7,5cm' => ['unidade', 100], // 100 gazes por pacote
        'Luva de procedimento P' => ['par', 50], // 1 par por pacote
        'Luva de procedimento M' => ['par', 50], // 1 par por pacote
        'Luva de procedimento G' => ['par', 50], // 1 par por pacote
        'Máscara Cirúrgica c/ 50' => ['unidade', 50], // 50 máscaras por caixa
        'Fita de dextro (on call plus II) c/ 50' => ['unidade', 50], // 50 máscaras por caixa
        'Clorexidina Degermante 2% (100ml)' => ['frasco', 1], // 1 frasco de 100ml
        'Iodopovidona 10%' => ['frasco', 1], // 1 frasco de 100ml
        'Soro Fisiológico 0,9% ampola' => ['unidade', 1], // 1 ampola
        'Soro Fisiológico 0,9% frasco (250ml)' => ['unidade', 1], // 1 ampola
        'Micropore' => ['unidade', 1], // A quantidade por pacote pode variar, mas assumimos 1 rolo
        'Esparadrapo' => ['unidade', 1], // A quantidade por pacote pode variar, mas assumimos 1 rolo
        'Curativo transparente (Band-Aid) c/ 10' => ['unidade', 10], // 10 unidades por pacote
        'Atadura crepom 10cm X 1,8m' => ['unidade', 1], // 1 rolo por pacote
        'Atadura crepom 15cm X 1,8m' => ['unidade', 1], // 1 rolo por pacote
        'Atadura crepom 20cm X 1,8m' => ['unidade', 1], // 1 rolo por pacote
        'Lençol papel hospitalar Maca' => ['unidade', 100], // 1 lençol por pacote
        'Lancetas Caixa c/ 100' => ['unidade', 100], // 1 lençol por pacote
        'Descarpack 13L' => ['unidade', 1], // 1 unidade por pacote
        'Benalet Pastilha c/ 12' => ['unidade', 12], // 12 pastilhas por pacote
        'Bilastina c/ 15' => ['unidade', 10], // 10 comprimidos por pacote
        'Buscofem c/ 10' => ['unidade', 20], // 20 comprimidos por pacote
        'Buscopan composto c/ 20' => ['unidade', 20], // 20 comprimidos por pacote
        'Cetoprofeno comp c/ 20' => ['unidade', 20], // 20 comprimidos por pacote
        'Cimegripe c/ 20' => ['unidade', 20], // 20 comprimidos por pacote
        'Decongex com 12' => ['unidade', 12], // 12 comprimidos por pacote
        'Diclofenaco Spray' => ['frasco', 1], // 1 frasco por pacote
        'Dipirona c/ 20' => ['unidade', 20], // 20 comprimidos por pacote
        'Diprogenta Pomada (30g)' => ['bisnaga', 1], // 30g por unidade
        'Epocler c/ 12' => ['unidade', 20], // 1 frasco por pacote
        'Floratil (Enterogermina Plus) c/ 12' => ['unidade', 20], // 1 frasco por pacote
        'Ibuprofeno 600mg c/ 10' => ['unidade', 20], // 20 comprimidos por pacote
        'Nebacetin Pomada 50 g' => ['bisnaga', 1], // 50g por unidade
        'Nimesulida comp c/ 12' => ['unidade', 12], // 12 comprimidos por pacote
        'Omeprazol Comprimido c? 28' => ['unidade', 28], // 28 comprimidos por pacote
        'Paracetamol comp c/ 20' => ['unidade', 20], // 20 comprimidos por pacote
        'Prednisolona Comprimido c/ 10' => ['unidade', 10], // 10 comprimidos por pacote
        'Torsilax c/ 12' => ['unidade', 10], // 10 comprimidos por pacote
        'Trok-N 30g' => ['bisnaga', 1], // 30g por unidade
        'Vonau 4mg c/ 10' => ['unidade', 30], // 30 comprimidos por pacote
        'Fita Métrica' => ['unidade', 1], // 30 comprimidos por pacote
        'Termogel Bolsa P/ Compressa' => ['unidade', 1], // 30 comprimidos por pacote
        'Aparelho de P.A.' => ['unidade', 1], // 30 comprimidos por pacote
        'Balança Digital' => ['unidade', 1], // 30 comprimidos por pacote
        'Bateria 2032 elgin' => ['unidade', 2], // 30 comprimidos por pacote
        'Glicosímetro' => ['unidade', 1], // 30 comprimidos por pacote
        'Termômetro' => ['unidade', 1], // 30 comprimidos por pacote
        'Oxímetro' => ['unidade', 1], // 30 comprimidos por pacote
        'Tesoura sem ponta' => ['unidade', 1], // 30 comprimidos por pacote
    ];
    
    
    public function run(): void
    {
        // Dados do Excel estruturados
        $dados = [
            // Betim
            'Betim' => [
                ['Algodão bolinha c/ 100', 750],
                ['Álcool 70% (100ml)', 15],
                ['Gaze 13 fios 7,5cm x 7,5cm', 300],
                ['Luva de procedimento P', 150],
                ['Luva de procedimento M', 150],
                ['Luva de procedimento G', 150],
                ['Máscara Cirúrgica c/ 50', 300],
                ['Clorexidina Degermante 2% (100ml)', 23],
                ['Iodopovidona 10%', 15],
                ['Soro Fisiológico 0,9% ampola', 300],
                ['Micropore', 15],
                ['Esparadrapo', 15],
                ['Curativo transparente (Band-Aid) c/ 10', 30],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 150],
                ['Descarpack 13L', 15],
                ['Benalet Pastilha c/ 12', 75],
                ['Bilastina c/ 15', 75],
                ['Buscofem c/ 10', 75],
                ['Buscopan composto c/ 20', 75],
                ['Cetoprofeno comp c/ 20', 75],
                ['Cimegripe c/ 20', 75],
                ['Decongex com 12', 75],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 75],
                ['Diprogenta Pomada (30g)', 3],
                ['Epocler c/ 12', 75],
                ['Floratil (Enterogermina Plus) c/ 12', 75],
                ['Ibuprofeno 600mg c/ 10', 75],
                ['Nebacetin Pomada 50 g', 2],
                ['Nimesulida comp c/ 12', 75],
                ['Omeprazol Comprimido c? 28', 75],
                ['Paracetamol comp c/ 20', 75],
                ['Prednisolona Comprimido c/ 10', 75],
                ['Torsilax c/ 12', 75],
                ['Trok-N 30g', 3],
                ['Vonau 4mg c/ 10', 75],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Guarulhos
            'Guarulhos' => [
                ['Algodão bolinha c/ 100', 889],
                ['Álcool 70% (100ml)', 18],
                ['Gaze 13 fios 7,5cm x 7,5cm', 356],
                ['Luva de procedimento P', 178],
                ['Luva de procedimento M', 178],
                ['Luva de procedimento G', 178],
                ['Máscara Cirúrgica c/ 50', 356],
                ['Clorexidina Degermante 2% (100ml)', 27],
                ['Iodopovidona 10%', 18],
                ['Soro Fisiológico 0,9% ampola', 356],
                ['Micropore', 17],
                ['Esparadrapo', 17],
                ['Curativo transparente (Band-Aid) c/ 10', 356],
                ['Atadura crepom 10cm X 1,8m', 2],
                ['Atadura crepom 15cm X 1,8m', 2],
                ['Atadura crepom 20cm X 1,8m', 2],
                ['Lençol papel hospitalar Maca', 178],
                ['Descarpack 13L', 18],
                ['Benalet Pastilha c/ 12', 89],
                ['Bilastina c/ 15', 89],
                ['Buscofem c/ 10', 89],
                ['Buscopan composto c/ 20', 89],
                ['Cetoprofeno comp c/ 20', 89],
                ['Cimegripe c/ 20', 89],
                ['Decongex com 12', 89],
                ['Diclofenaco Spray', 2],
                ['Dipirona c/ 20', 89],
                ['Diprogenta Pomada (30g)', 3],
                ['Epocler c/ 12', 89],
                ['Floratil (Enterogermina Plus) c/ 12', 89],
                ['Ibuprofeno 600mg c/ 10', 89],
                ['Nebacetin Pomada 50 g', 2],
                ['Nimesulida comp c/ 12', 89],
                ['Omeprazol Comprimido c/ 28', 89],
                ['Paracetamol comp c/ 20', 89],
                ['Prednisolona Comprimido c/ 10', 89],
                ['Torsilax c/ 12', 89],
                ['Trok-N 30g', 3],
                ['Vonau 4mg c/ 10', 89],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Santana de Parnaiba
            'Santana de Parnaiba' => [
                ['Algodão bolinha c/ 100', 1309],
                ['Álcool 70% (100ml)', 26],
                ['Gaze 13 fios 7,5cm x 7,5cm', 524],
                ['Luva de procedimento P', 262],
                ['Luva de procedimento M', 262],
                ['Luva de procedimento G', 262],
                ['Máscara Cirúrgica c/ 50', 524],
                ['Clorexidina Degermante 2% (100ml)', 40],
                ['Iodopovidona 10%', 26],
                ['Soro Fisiológico 0,9% ampola', 524],
                ['Micropore', 26],
                ['Esparadrapo', 26],
                ['Curativo transparente (Band-Aid) c/ 10', 524],
                ['Atadura crepom 10cm X 1,8m', 3],
                ['Atadura crepom 15cm X 1,8m', 3],
                ['Atadura crepom 20cm X 1,8m', 3],
                ['Lençol papel hospitalar Maca', 262],
                ['Descarpack 13L', 26],
                ['Benalet Pastilha c/ 12', 131],
                ['Bilastina c/ 15', 131],
                ['Buscofem c/ 10', 131],
                ['Buscopan composto c/ 20', 131],
                ['Cetoprofeno comp c/ 20', 131],
                ['Cimegripe c/ 20', 131],
                ['Decongex com 12', 131],
                ['Diclofenaco Spray', 2],
                ['Dipirona c/ 20', 131],
                ['Diprogenta Pomada (30g)', 5],
                ['Epocler c/ 12', 131],
                ['Floratil (Enterogermina Plus) c/ 12', 131],
                ['Ibuprofeno 600mg c/ 10', 131],
                ['Nebacetin Pomada 50 g', 3],
                ['Nimesulida comp c/ 12', 131],
                ['Omeprazol Comprimido c/ 28', 131],
                ['Paracetamol comp c/ 20', 131],
                ['Prednisolona Comprimido c/ 10', 131],
                ['Torsilax c/ 12', 131],
                ['Trok-N 30g', 5],
                ['Vonau 4mg c/ 10', 131],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Simões Filho
            'Simões Filho' => [
                ['Algodão bolinha c/ 100', 459],
                ['Álcool 70% (100ml)', 9],
                ['Gaze 13 fios 7,5cm x 7,5cm', 184],
                ['Luva de procedimento P', 92],
                ['Luva de procedimento M', 92],
                ['Luva de procedimento G', 92],
                ['Máscara Cirúrgica c/ 50', 184],
                ['Clorexidina Degermante 2% (100ml)', 14],
                ['Iodopovidona 10%', 9],
                ['Soro Fisiológico 0,9% ampola', 184],
                ['Micropore', 9],
                ['Esparadrapo', 9],
                ['Curativo transparente (Band-Aid) c/ 10', 184],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 92],
                ['Descarpack 13L', 9],
                ['Benalet Pastilha c/ 12', 46],
                ['Bilastina c/ 15', 46],
                ['Buscofem c/ 10', 46],
                ['Buscopan composto c/ 20', 46],
                ['Cetoprofeno comp c/ 20', 46],
                ['Cimegripe c/ 20', 46],
                ['Decongex com 12', 46],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 46],
                ['Diprogenta Pomada (30g)', 2],
                ['Epocler c/ 12', 46],
                ['Floratil (Enterogermina Plus) c/ 12', 46],
                ['Ibuprofeno 600mg c/ 10', 46],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 46],
                ['Omeprazol Comprimido c/ 28', 46],
                ['Paracetamol comp c/ 20', 46],
                ['Prednisolona Comprimido c/ 10', 46],
                ['Torsilax c/ 12', 46],
                ['Trok-N 30g', 2],
                ['Vonau 4mg c/ 10', 46],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Cravinhos
            'Cravinhos' => [
                ['Algodão bolinha c/ 100', 546],
                ['Álcool 70% (100ml)', 11],
                ['Gaze 13 fios 7,5cm x 7,5cm', 219],
                ['Luva de procedimento P', 109],
                ['Luva de procedimento M', 109],
                ['Luva de procedimento G', 109],
                ['Máscara Cirúrgica c/ 50', 219],
                ['Clorexidina Degermante 2% (100ml)', 17],
                ['Iodopovidona 10%', 11],
                ['Soro Fisiológico 0,9% ampola', 219],
                ['Micropore', 11],
                ['Esparadrapo', 11],
                ['Curativo transparente (Band-Aid) c/ 10', 219],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 109],
                ['Descarpack 13L', 11],
                ['Benalet Pastilha c/ 12', 55],
                ['Bilastina c/ 15', 55],
                ['Buscofem c/ 10', 55],
                ['Buscopan composto c/ 20', 55],
                ['Cetoprofeno comp c/ 20', 55],
                ['Cimegripe c/ 20', 55],
                ['Decongex com 12', 55],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 55],
                ['Diprogenta Pomada (30g)', 2],
                ['Epocler c/ 12', 55],
                ['Floratil (Enterogermina Plus) c/ 12', 55],
                ['Ibuprofeno 600mg c/ 10', 55],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 55],
                ['Omeprazol Comprimido c/ 28', 55],
                ['Paracetamol comp c/ 20', 55],
                ['Prednisolona Comprimido c/ 10', 55],
                ['Torsilax c/ 12', 55],
                ['Trok-N 30g', 2],
                ['Vonau 4mg c/ 10', 55],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Cabo de Sto Agostinho
            'Cabo de Santo Agostinho' => [
                ['Algodão bolinha c/ 100', 404],
                ['Álcool 70% (100ml)', 8],
                ['Gaze 13 fios 7,5cm x 7,5cm', 162],
                ['Luva de procedimento P', 81],
                ['Luva de procedimento M', 81],
                ['Luva de procedimento G', 81],
                ['Máscara Cirúrgica c/ 50', 162],
                ['Clorexidina Degermante 2% (100ml)', 12],
                ['Iodopovidona 10%', 8],
                ['Soro Fisiológico 0,9% ampola', 162],
                ['Micropore', 8],
                ['Esparadrapo', 8],
                ['Curativo transparente (Band-Aid) c/ 10', 162],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 81],
                ['Descarpack 13L', 8],
                ['Benalet Pastilha c/ 12', 40],
                ['Bilastina c/ 15', 40],
                ['Buscofem c/ 10', 40],
                ['Buscopan composto c/ 20', 40],
                ['Cetoprofeno comp c/ 20', 40],
                ['Cimegripe c/ 20', 40],
                ['Decongex com 12', 40],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 40],
                ['Diprogenta Pomada (30g)', 2],
                ['Epocler c/ 12', 40],
                ['Floratil (Enterogermina Plus) c/ 12', 40],
                ['Ibuprofeno 600mg c/ 10', 40],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 40],
                ['Omeprazol Comprimido c/ 28', 40],
                ['Paracetamol comp c/ 20', 40],
                ['Prednisolona Comprimido c/ 10', 40],
                ['Torsilax c/ 12', 40],
                ['Trok-N 30g', 2],
                ['Vonau 4mg c/ 10', 40],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Gravatai
            'Gravatai' => [
                ['Algodão bolinha c/ 100', 256],
                ['Álcool 70% (100ml)', 5],
                ['Gaze 13 fios 7,5cm x 7,5cm', 103],
                ['Luva de procedimento P', 51],
                ['Luva de procedimento M', 51],
                ['Luva de procedimento G', 51],
                ['Máscara Cirúrgica c/ 50', 103],
                ['Clorexidina Degermante 2% (100ml)', 8],
                ['Iodopovidona 10%', 5],
                ['Soro Fisiológico 0,9% ampola', 103],
                ['Micropore', 5],
                ['Esparadrapo', 5],
                ['Curativo transparente (Band-Aid) c/ 10', 103],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 51],
                ['Descarpack 13L', 5],
                ['Benalet Pastilha c/ 12', 26],
                ['Bilastina c/ 15', 26],
                ['Buscofem c/ 10', 26],
                ['Buscopan composto c/ 20', 26],
                ['Cetoprofeno comp c/ 20', 26],
                ['Cimegripe c/ 20', 26],
                ['Decongex com 12', 26],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 26],
                ['Diprogenta Pomada (30g)', 1],
                ['Epocler c/ 12', 26],
                ['Floratil (Enterogermina Plus) c/ 12', 26],
                ['Ibuprofeno 600mg c/ 10', 26],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 26],
                ['Omeprazol Comprimido c/ 28', 26],
                ['Paracetamol comp c/ 20', 26],
                ['Prednisolona Comprimido c/ 10', 26],
                ['Torsilax c/ 12', 26],
                ['Trok-N 30g', 1],
                ['Vonau 4mg c/ 10', 26],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Louveira
            'Louveira' => [
                ['Algodão bolinha c/ 100', 508],
                ['Álcool 70% (100ml)', 10],
                ['Gaze 13 fios 7,5cm x 7,5cm', 203],
                ['Luva de procedimento P', 102],
                ['Luva de procedimento M', 102],
                ['Luva de procedimento G', 102],
                ['Máscara Cirúrgica c/ 50', 203],
                ['Clorexidina Degermante 2% (100ml)', 15],
                ['Iodopovidona 10%', 10],
                ['Soro Fisiológico 0,9% ampola', 203],
                ['Micropore', 10],
                ['Esparadrapo', 10],
                ['Curativo transparente (Band-Aid) c/ 10', 203],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 102],
                ['Descarpack 13L', 10],
                ['Benalet Pastilha c/ 12', 51],
                ['Bilastina c/ 15', 51],
                ['Buscofem c/ 10', 51],
                ['Buscopan composto c/ 20', 51],
                ['Cetoprofeno comp c/ 20', 51],
                ['Cimegripe c/ 20', 51],
                ['Decongex com 12', 51],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 51],
                ['Diprogenta Pomada (30g)', 2],
                ['Epocler c/ 12', 51],
                ['Floratil (Enterogermina Plus) c/ 12', 51],
                ['Ibuprofeno 600mg c/ 10', 51],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 51],
                ['Omeprazol Comprimido c/ 28', 51],
                ['Paracetamol comp c/ 20', 51],
                ['Prednisolona Comprimido c/ 10', 51],
                ['Torsilax c/ 12', 51],
                ['Trok-N 30g', 2],
                ['Vonau 4mg c/ 10', 51],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Hidrolandia
            'Hidrolandia' => [
                ['Algodão bolinha c/ 100', 333],
                ['Álcool 70% (100ml)', 7],
                ['Gaze 13 fios 7,5cm x 7,5cm', 133],
                ['Luva de procedimento P', 67],
                ['Luva de procedimento M', 67],
                ['Luva de procedimento G', 67],
                ['Máscara Cirúrgica c/ 50', 133],
                ['Clorexidina Degermante 2% (100ml)', 10],
                ['Iodopovidona 10%', 7],
                ['Soro Fisiológico 0,9% ampola', 133],
                ['Micropore', 6],
                ['Esparadrapo', 6],
                ['Curativo transparente (Band-Aid) c/ 10', 133],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 67],
                ['Descarpack 13L', 7],
                ['Benalet Pastilha c/ 12', 33],
                ['Bilastina c/ 15', 33],
                ['Buscofem c/ 10', 33],
                ['Buscopan composto c/ 20', 33],
                ['Cetoprofeno comp c/ 20', 33],
                ['Cimegripe c/ 20', 33],
                ['Decongex com 12', 33],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 33],
                ['Diprogenta Pomada (30g)', 2],
                ['Epocler c/ 12', 33],
                ['Floratil (Enterogermina Plus) c/ 12', 33],
                ['Ibuprofeno 600mg c/ 10', 33],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 33],
                ['Omeprazol Comprimido c/ 28', 33],
                ['Paracetamol comp c/ 20', 33],
                ['Prednisolona Comprimido c/ 10', 33],
                ['Torsilax c/ 12', 33],
                ['Trok-N 30g', 1],
                ['Vonau 4mg c/ 10', 33],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // São João de Meriti
            'São João de Meriti' => [
                ['Algodão bolinha c/ 100', 551],
                ['Álcool 70% (100ml)', 11],
                ['Gaze 13 fios 7,5cm x 7,5cm', 221],
                ['Luva de procedimento P', 110],
                ['Luva de procedimento M', 110],
                ['Luva de procedimento G', 110],
                ['Máscara Cirúrgica c/ 50', 221],
                ['Clorexidina Degermante 2% (100ml)', 17],
                ['Iodopovidona 10%', 11],
                ['Soro Fisiológico 0,9% ampola', 221],
                ['Micropore', 11],
                ['Esparadrapo', 11],
                ['Curativo transparente (Band-Aid) c/ 10', 221],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 110],
                ['Descarpack 13L', 11],
                ['Benalet Pastilha c/ 12', 55],
                ['Bilastina c/ 15', 55],
                ['Buscofem c/ 10', 55],
                ['Buscopan composto c/ 20', 55],
                ['Cetoprofeno comp c/ 20', 55],
                ['Cimegripe c/ 20', 55],
                ['Decongex com 12', 55],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 55],
                ['Diprogenta Pomada (30g)', 2],
                ['Epocler c/ 12', 55],
                ['Floratil (Enterogermina Plus) c/ 12', 55],
                ['Ibuprofeno 600mg c/ 10', 55],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 55],
                ['Omeprazol Comprimido c/ 28', 55],
                ['Paracetamol comp c/ 20', 55],
                ['Prednisolona Comprimido c/ 10', 55],
                ['Torsilax c/ 12', 55],
                ['Trok-N 30g', 2],
                ['Vonau 4mg c/ 10', 55],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Duque de Caxias
            'Duque de Caxias' => [
                ['Algodão bolinha c/ 100', 235],
                ['Álcool 70% (100ml)', 5],
                ['Gaze 13 fios 7,5cm x 7,5cm', 94],
                ['Luva de procedimento P', 47],
                ['Luva de procedimento M', 47],
                ['Luva de procedimento G', 47],
                ['Máscara Cirúrgica c/ 50', 94],
                ['Clorexidina Degermante 2% (100ml)', 7],
                ['Iodopovidona 10%', 5],
                ['Soro Fisiológico 0,9% ampola', 94],
                ['Micropore', 4],
                ['Esparadrapo', 4],
                ['Curativo transparente (Band-Aid) c/ 10', 94],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 47],
                ['Descarpack 13L', 5],
                ['Benalet Pastilha c/ 12', 24],
                ['Bilastina c/ 15', 24],
                ['Buscofem c/ 10', 24],
                ['Buscopan composto c/ 20', 24],
                ['Cetoprofeno comp c/ 20', 24],
                ['Cimegripe c/ 20', 24],
                ['Decongex com 12', 24],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 24],
                ['Diprogenta Pomada (30g)', 1],
                ['Epocler c/ 12', 24],
                ['Floratil (Enterogermina Plus) c/ 12', 24],
                ['Ibuprofeno 600mg c/ 10', 24],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 24],
                ['Omeprazol Comprimido c/ 28', 24],
                ['Paracetamol comp c/ 20', 24],
                ['Prednisolona Comprimido c/ 10', 24],
                ['Torsilax c/ 12', 24],
                ['Trok-N 30g', 1],
                ['Vonau 4mg c/ 10', 24],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Franco da Rocha
            'Franco da Rocha' => [
                ['Algodão bolinha c/ 100', 33],
                ['Álcool 70% (100ml)', 1],
                ['Gaze 13 fios 7,5cm x 7,5cm', 13],
                ['Luva de procedimento P', 7],
                ['Luva de procedimento M', 7],
                ['Luva de procedimento G', 7],
                ['Máscara Cirúrgica c/ 50', 13],
                ['Clorexidina Degermante 2% (100ml)', 1],
                ['Iodopovidona 10%', 1],
                ['Soro Fisiológico 0,9% ampola', 13],
                ['Micropore', 1],
                ['Esparadrapo', 1],
                ['Curativo transparente (Band-Aid) c/ 10', 13],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 7],
                ['Descarpack 13L', 1],
                ['Benalet Pastilha c/ 12', 3],
                ['Bilastina c/ 15', 3],
                ['Buscofem c/ 10', 3],
                ['Buscopan composto c/ 20', 3],
                ['Cetoprofeno comp c/ 20', 3],
                ['Cimegripe c/ 20', 3],
                ['Decongex com 12', 3],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 3],
                ['Diprogenta Pomada (30g)', 3],
                ['Epocler c/ 12', 3],
                ['Floratil (Enterogermina Plus) c/ 12', 3],
                ['Ibuprofeno 600mg c/ 10', 3],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 3],
                ['Omeprazol Comprimido c/ 28', 3],
                ['Paracetamol comp c/ 20', 3],
                ['Prednisolona Comprimido c/ 10', 3],
                ['Torsilax c/ 12', 3],
                ['Trok-N 30g', 1],
                ['Vonau 4mg c/ 10', 3],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // PLAZA-SP
            'PLAZA-SP' => [
                ['Algodão bolinha c/ 100', 1046],
                ['Álcool 70% (100ml)', 21],
                ['Gaze 13 fios 7,5cm x 7,5cm', 419],
                ['Luva de procedimento P', 209],
                ['Luva de procedimento M', 209],
                ['Luva de procedimento G', 209],
                ['Máscara Cirúrgica c/ 50', 419],
                ['Clorexidina Degermante 2% (100ml)', 31],
                ['Iodopovidona 10%', 21],
                ['Soro Fisiológico 0,9% ampola', 419],
                ['Micropore', 21],
                ['Esparadrapo', 21],
                ['Curativo transparente (Band-Aid) c/ 10', 419],
                ['Atadura crepom 10cm X 1,8m', 2],
                ['Atadura crepom 15cm X 1,8m', 2],
                ['Atadura crepom 20cm X 1,8m', 2],
                ['Lençol papel hospitalar Maca', 209],
                ['Descarpack 13L', 21],
                ['Benalet Pastilha c/ 12', 105],
                ['Bilastina c/ 15', 105],
                ['Buscofem c/ 10', 105],
                ['Buscopan composto c/ 20', 105],
                ['Cetoprofeno comp c/ 20', 105],
                ['Cimegripe c/ 20', 105],
                ['Decongex com 12', 105],
                ['Diclofenaco Spray', 2],
                ['Dipirona c/ 20', 105],
                ['Diprogenta Pomada (30g)', 4],
                ['Epocler c/ 12', 105],
                ['Floratil (Enterogermina Plus) c/ 12', 105],
                ['Ibuprofeno 600mg c/ 10', 105],
                ['Nebacetin Pomada 50 g', 2],
                ['Nimesulida comp c/ 12', 105],
                ['Omeprazol Comprimido c/ 28', 105],
                ['Paracetamol comp c/ 20', 105],
                ['Prednisolona Comprimido c/ 10', 105],
                ['Torsilax c/ 12', 105],
                ['Trok-N 30g', 4],
                ['Vonau 4mg c/ 10', 105],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Campina Grande
            'Campina Grande do Sul' => [
                ['Algodão bolinha c/ 100', 58],
                ['Álcool 70% (100ml)', 2],
                ['Gaze 13 fios 7,5cm x 7,5cm', 23],
                ['Luva de procedimento P', 12],
                ['Luva de procedimento M', 12],
                ['Luva de procedimento G', 12],
                ['Máscara Cirúrgica c/ 50', 23],
                ['Clorexidina Degermante 2% (100ml)', 2],
                ['Iodopovidona 10%', 1],
                ['Soro Fisiológico 0,9% ampola', 23],
                ['Micropore', 1],
                ['Esparadrapo', 1],
                ['Curativo transparente (Band-Aid) c/ 10', 23],
                ['Atadura crepom 10cm X 1,8m', 1],
                ['Atadura crepom 15cm X 1,8m', 1],
                ['Atadura crepom 20cm X 1,8m', 1],
                ['Lençol papel hospitalar Maca', 12],
                ['Descarpack 13L', 1],
                ['Benalet Pastilha c/ 12', 6],
                ['Bilastina c/ 15', 6],
                ['Buscofem c/ 10', 6],
                ['Buscopan composto c/ 20', 6],
                ['Cetoprofeno comp c/ 20', 6],
                ['Cimegripe c/ 20', 6],
                ['Decongex com 12', 6],
                ['Diclofenaco Spray', 1],
                ['Dipirona c/ 20', 6],
                ['Diprogenta Pomada (30g)', 1],
                ['Epocler c/ 12', 6],
                ['Floratil (Enterogermina Plus) c/ 12', 6],
                ['Ibuprofeno 600mg c/ 10', 6],
                ['Nebacetin Pomada 50 g', 1],
                ['Nimesulida comp c/ 12', 6],
                ['Omeprazol Comprimido c/ 28', 6],
                ['Paracetamol comp c/ 20', 6],
                ['Prednisolona Comprimido c/ 10', 6],
                ['Torsilax c/ 12', 6],
                ['Trok-N 30g', 1],
                ['Vonau 4mg c/ 10', 6],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Matriz B32
            'Matriz B32' => [
                ['Algodão bolinha c/ 100', 2059],
                ['Álcool 70% (100ml)', 41],
                ['Gaze 13 fios 7,5cm x 7,5cm', 824],
                ['Luva de procedimento P', 412],
                ['Luva de procedimento M', 412],
                ['Luva de procedimento G', 412],
                ['Máscara Cirúrgica c/ 50', 824],
                ['Clorexidina Degermante 2% (100ml)', 62],
                ['Iodopovidona 10%', 41],
                ['Soro Fisiológico 0,9% ampola', 824],
                ['Micropore', 41],
                ['Esparadrapo', 41],
                ['Curativo transparente (Band-Aid) c/ 10', 82],
                ['Atadura crepom 10cm X 1,8m', 4],
                ['Atadura crepom 15cm X 1,8m', 4],
                ['Atadura crepom 20cm X 1,8m', 4],
                ['Lençol papel hospitalar Maca', 412],
                ['Descarpack 13L', 41],
                ['Benalet Pastilha c/ 12', 206],
                ['Bilastina c/ 15', 206],
                ['Buscofem c/ 10', 206],
                ['Buscopan composto c/ 20', 206],
                ['Cetoprofeno comp c/ 20', 206],
                ['Cimegripe c/ 20', 206],
                ['Decongex com 12', 206],
                ['Diclofenaco Spray', 206],
                ['Dipirona c/ 20', 206],
                ['Diprogenta Pomada (30g)', 206],
                ['Epocler c/ 12', 206],
                ['Floratil (Enterogermina Plus) c/ 12', 206],
                ['Ibuprofeno 600mg c/ 10', 206],
                ['Nebacetin Pomada 50 g', 206],
                ['Nimesulida comp c/ 12', 206],
                ['Omeprazol Comprimido c/ 28', 206],
                ['Paracetamol comp c/ 20', 206],
                ['Prednisolona Comprimido c/ 10', 206],
                ['Torsilax c/ 12', 206],
                ['Trok-N 30g', 206],
                ['Vonau 4mg c/ 10', 206],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
            // Matriz B32
            'Matriz FLP' => [
                ['Algodão bolinha c/ 100', 2059],
                ['Álcool 70% (100ml)', 41],
                ['Gaze 13 fios 7,5cm x 7,5cm', 824],
                ['Luva de procedimento P', 412],
                ['Luva de procedimento M', 412],
                ['Luva de procedimento G', 412],
                ['Máscara Cirúrgica c/ 50', 824],
                ['Clorexidina Degermante 2% (100ml)', 62],
                ['Iodopovidona 10%', 41],
                ['Soro Fisiológico 0,9% ampola', 824],
                ['Micropore', 41],
                ['Esparadrapo', 41],
                ['Curativo transparente (Band-Aid) c/ 10', 82],
                ['Atadura crepom 10cm X 1,8m', 4],
                ['Atadura crepom 15cm X 1,8m', 4],
                ['Atadura crepom 20cm X 1,8m', 4],
                ['Lençol papel hospitalar Maca', 412],
                ['Descarpack 13L', 41],
                ['Benalet Pastilha c/ 12', 206],
                ['Bilastina c/ 15', 206],
                ['Buscofem c/ 10', 206],
                ['Buscopan composto c/ 20', 206],
                ['Cetoprofeno comp c/ 20', 206],
                ['Cimegripe c/ 20', 206],
                ['Decongex com 12', 206],
                ['Diclofenaco Spray', 206],
                ['Dipirona c/ 20', 206],
                ['Diprogenta Pomada (30g)', 206],
                ['Epocler c/ 12', 206],
                ['Floratil (Enterogermina Plus) c/ 12', 206],
                ['Ibuprofeno 600mg c/ 10', 206],
                ['Nebacetin Pomada 50 g', 206],
                ['Nimesulida comp c/ 12', 206],
                ['Omeprazol Comprimido c/ 28', 206],
                ['Paracetamol comp c/ 20', 206],
                ['Prednisolona Comprimido c/ 10', 206],
                ['Torsilax c/ 12', 206],
                ['Trok-N 30g', 206],
                ['Vonau 4mg c/ 10', 206],
                ['Fita Métrica', 1],
                ['Termogel Bolsa P/ Compressa', 1],
                ['Fita de dextro (on call plus II) c/ 50', 1],
                ['Absorvente Mili Noturno c/ 32', 1],
                ['Absorvente Mili Simples c/ 32', 1],
                ['Lancetas Caixa c/ 100', 1],
                ['Soro Fisiológico 0,9% frasco (250ml)', 1],
                ['Álcool 70% (Swaab) c/ 200', 1],
                ['Aparelho de P.A.', 1],
                ['Balança Digital', 1],
                ['Bateria 2032 elgin', 2],
                ['Glicosímetro', 1],
                ['Termômetro', 2],
                ['Oxímetro', 1],
                ['Tesoura sem ponta', 1],
            ],
        ];

// Primeiro, criamos todos os insumos únicos com suas unidades de medida
foreach ($this->insumosComMedida as $nomeInsumo => $detalhes) {
    list($unidadeMedida, $unidadesPorPacote) = $detalhes;
    $insumo = Insumo::firstOrCreate(
        ['nome' => $nomeInsumo],
        ['unidade_medida' => $unidadeMedida]
    );

    // Agora associamos com cada unidade (team)
    foreach ($dados as $nomeUnidade => $insumos) {
        $team = Team::where('name', $nomeUnidade)->first();

        if (!$team) {
            continue; // Pula se a unidade não existir
        }

        foreach ($insumos as $insumoData) {
            $nomeInsumo = $insumoData[0];
            $quantidadeMinima = $insumoData[1];

            $insumoModel = Insumo::where('nome', $nomeInsumo)->first();

            if ($insumoModel) {
                // Verifica se o relacionamento já existe
                $existe = DB::table('insumo_team')
                    ->where('insumo_id', $insumoModel->id)
                    ->where('team_id', $team->id)
                    ->exists();

                if (!$existe) {
                    $team->insumos()->attach($insumoModel->id, [
                        'quantidade_minima' => $quantidadeMinima,
                        'quantidade_existente' => 0, // Inicia com 0
                        'unidades_por_pacote' => $unidadesPorPacote, // Adiciona a quantidade por pacote
                    ]);
                }
            }
        }
    }
}
    }
}