version: '3.8'

services:
  c3stock_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.4-fpm
    container_name: c3stock_app_dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - c3stock_db_dev
      - c3stock_node_dev
    networks:
      - c3stock_dev

  c3stock_node_dev:
    image: node:18
    container_name: c3stock_node_dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: tail -f /dev/null
    ports:
      - "5180:5176"  # Porta externa alterada para 5180
    networks:
      - c3stock_dev

  c3stock_nginx_dev:
    depends_on:
      - c3stock_app_dev
    image: nginx:alpine
    container_name: c3stock_nginx_dev
    ports:
      - "8084:80"  # Porta diferente do prod
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Agora está correto
    networks:
      - c3stock_dev

  c3stock_db_dev:
    image: mysql:8.0
    container_name: c3stock_db_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: c3stock_dev
      MYSQL_USER: c3stock_user_dev
      MYSQL_PASSWORD: c3stock_password_dev
    volumes:
      - dbdata_c3stock_dev:/var/lib/mysql
    networks:
      - c3stock_dev

networks:
  c3stock_dev:

volumes:
  dbdata_c3stock_dev:
